cloudscape-design/theming-core

- src/build/tasks/postcss/index.ts
Description of changes:
Remove IE11 from browserlist config.
https://aws.amazon.com/blogs/aws/heads-up-aws-support-for-internet-explorer-11-is-ending/
> chore: Remove IE11 from browserslist config

- package-lock.json
- package.json
- scripts/generate-package
- src/build/__tests__/public.test.ts
- src/build/tasks/postcss/index.ts
We recently removed IE11 from browserslists configuration, however we kept fallback PostCSS plugin for CSS Custom Properties. We are removing it here. 
> chore: Remove Custom Property plugin

- package-lock.json
- package.json
Downgrade to last version, which does not contain `sass-embedded`, which has been included in `1.49.1`. I suspect the loading as changed at this point. 
Large diff is due to removal of first part dependency `@cloudscape-design/browser-test-tool` and it's dependencies from the lockfile. 
> chore: Downgrade SASS to 1.49.0

- jest.browser.config.js
- jest.build.config.js
- jest.integ.config.js
*Issue #, if available:* n/a
Make sure that all code coverage reports from the different `test:*` runs are saved in separate folders.
Putting them all in one `coverage` folder makes sure that codecov can merge all reports correctly.
> chore: Merge code coverage reports

- package-lock.json
- scripts/unlock-packages.js
*Description of changes:* This change makes sure that the unlock script works with the new `package-lock.json` format in npm v8.
> chore: Update unlock script for npm v8

- package-lock.json
Regenerate package-lock.
This [PR](https://github.com/cloudscape-design/theming-core/pull/31) from dependabot added the cloudscape packages to the package-lock file. The change is a mistake due to the way the `preinstall` npm script was changed in npm 8.
> chore: Remove cloudscape deps from package-lock

- src/__fixtures__/common.ts
- src/shared/theme/__tests__/merge.test.ts
- src/shared/theme/merge.ts
> fix: Ignore overriden contexts that do not exist in the theme

- src/__fixtures__/common.ts
- src/browser/__tests__/__snapshots__/index.test.ts.snap
- src/build/tasks/__tests__/__snapshots__/preset.test.ts.snap
- src/shared/declaration/__tests__/__snapshots__/index.test.ts.snap
- src/shared/declaration/multi.ts
- src/shared/declaration/rule.ts
- src/shared/declaration/single.ts
- src/shared/declaration/stylesheet.ts
- src/shared/theme/__tests__/__snapshots__/merge.test.ts.snap
- src/shared/theme/interfaces.ts
Add support for media queries in optional modes, so that we can limit dark mode to non-print media.
See also https://github.com/cloudscape-design/components/pull/1204
> feat: Support media queries in optional modes

- package-lock.json
- package.json
- scripts/generate-package
- src/__fixtures__/common.ts
- src/build/internal.ts
- src/build/tasks/__tests__/public-tokens.test.ts
- src/build/tasks/__tests__/theme-json-schema.test.ts
- src/build/tasks/public-tokens.ts
- src/build/tasks/theme-json-schema.ts
- src/build/tasks/theme-json.ts
> feat: Generate JSON schema and validate

- package-lock.json
- package.json
Fixed vulnerabilities from `npm audit`
> chore: Update postcss-inline-svg

- src/__fixtures__/common.ts
- src/shared/theme/__tests__/resolve.test.ts
- src/shared/theme/resolve.ts
the thrown error when resolving a token that doesn't have any mode value does not have data about the token and modes
> chore: Add more logging to resolve token mode error handling

- src/build/tasks/copy.ts
N/A
Currently, buildThemedComponents on Windows does not correctly generate the destination directory. This is because on Windows, `mkdir -p` is generating a directory named `-p` instead of the destination ([see also](https://superuser.com/a/816355)).
```
A subdirectory or file -p already exists.
Error occurred while processing: -p.
node:internal/errors:867
const err = new Error(message);
^
Error: Command failed: mkdir -p dist\themed\design-tokens
```
This change switches to using `fs.mkdirSync` for better compatibility on Windows.
Built `@cloudscape-design/theming-build` on my Windows machine and copied theming build artifacts to node_modules in my custom theme. Did fresh build of custom theme and did not encounter `-p` folder issue …
> fix: use mkdirSync and cpSync in copy

- package-lock.json
- package.json
- scripts/generate-package
- src/build/tasks/postcss/index.ts
- typings/postcss-initial.d.ts
This PR removes the `postcss-initial` plugin from theming core. This package is incompatible with our RTL initiative as it sets the `direction` attribute to `ltr` instead of `inherit`. Given the package appears to be no longer maintained, we are removing it and replacing the use of `all: initial` in our styles reset to a [manual list of properties](https://github.com/cloudscape-design/components/pull/1876).
> chore: Remove postcss-initial plugin

- src/browser/__tests__/__snapshots__/index.test.ts.snap
- src/browser/__tests__/dom.test.ts
- src/browser/__tests__/index.test.ts
- src/browser/dom.ts
- src/browser/index.ts
N/A
Adds support for an optional 'target document' parameter for the applyTheme function. This enables the application of a theme to an HTML document other than the current document, such as an iframe.
> feat: Support optional target document for applyTheme

- src/build/internal.ts
- src/build/tasks/__tests__/__snapshots__/internal-tokens.test.ts.snap
- src/build/tasks/__tests__/internal-tokens.test.ts
- src/build/tasks/internal-tokens.ts
Fixing a misalignment between SASS and JS. In SASS, we can use `space-s` internally, but in JS we can't.
External token files are not affected because they are handled by separate code
---
> chore: Explose the entire token set internally

- package-lock.json
- package.json
- src/build/__tests__/__fixtures__/scss-advanced/button/styles.scss
- src/build/tasks/style.ts
Allow e.g. `@use '@cloudscape-design/component-toolkit/internal/focus-visible' as focus-visible;` in SASS files.
> chore: Support @cloudscape-design npm-style imports in sass

- src/build/index.ts
Follow up for this change: https://github.com/cloudscape-design/components/pull/2075.
We are fine across all our packages now: https://github.com/search?q=org%3Acloudscape-design%20buildThemedComponentsInternal&type=code
> fix: Remove internal exports from the public API

- package-lock.json
- package.json
- src/build/__tests__/__fixtures__/scss-only/mixed-declarations/styles.scss
- src/build/__tests__/styles.test.ts
- src/build/internal.ts
- src/build/tasks/style.ts
*Issue #, if available:* https://github.com/cloudscape-design/components/issues/2571
Detect and fail when deprecation warnings mentioned in https://github.com/cloudscape-design/components/issues/2571 are found.
Made this an opt-in flag to allow gradual migration for our existing code.
---
I explored an alternative option about stylelint rule, but this is not possible to detect this case using stylelint, because it requires actual compliation of the sass code, to see where the issue happens
---
> feat: Allow to fail the build when sass deprecation warnings found

- src/build/tasks/style.ts
Print stack information with a deprecation warning. This will help to find their locations and fix
> feat: add stack info when printing deprecation warning

- package-lock.json
- package.json
This upgrades in turn esbuild to `^0.25.0`.
> chore: Upgrade vite to v3.0.7

- package-lock.json
*Description of changes: Ran `npm audit fix` to address [dependabot alert](https://github.com/cloudscape-design/theming-core/security/dependabot/51)
> chore: Bump axios and vite
